import random
from colorist import ColorHex

def random_num(lv):
    x = random.randint(1, lv)
    return x

def guessing(x):
    while True:
        g = input("\nGuess a number (or 'exit'): ")

        if g == 'exit':
            return "You have exited the game."

        try:
            g = int(g)

            if g > x:
                print("Your number is larger!")
            elif g < x:
                print("Your number is smaller!")
            else:
                return f"Well done! The number was: {x}"

        except ValueError:
            print("Please enter a number (int) or type `exit`.")


def main():
    print(f"""\nYour goal is to guess the random number generated by the computer in the shortest guesses possible. Choose the level, how high the number that is generated can be, e.g: from 1 - 50. 
It will give you hints (higher or lower) if you guess incorrectly. Type `exit` at anytime to end the game.""")

    while True:
        try:
            level = input("\nChoose a level (or 'exit'): ")
            if level == 'exit':
                return "You have exited the game."

            level = int(level)
            if level > 0:
                break
            else: 
                raise TypeError

        except TypeError:
            print("Please enter a valid number (int > 0) or type `exit`.") 
        except ValueError:
            print("Please enter a number (int) or type `exit`.") 

    x = random_num(level)   
    print(guessing(x))


if __name__ == "__main__":
    main()