# game - Guessing game (different levels of difficulty, user must guess a random number generated by programm, runs until number is guessed, or user exits.
# lvl of difficulty to be added at a later time

import random
from colorist import ColorHex

def random_num(n):
    rand = random.randint(1,3)
    if n == rand:
        return 'Good Job!'
    else:
        return 'Nope!'

def main():
    number = int(input('Guess a number: '))
    print(random_num(number))

if __name__ == "__main__":
    main()