import random

def random_num(lv):
    x = random.randint(1, lv)
    return x

def guessing(x):
    tries = 1

    while True:
        g = input("Guess a number (or 'exit'): ")

        if g.strip() == 'exit':
            return "You have exited the game."

        try:
            g = int(g)
            if g > x:
                print("Your number is larger!")
                tries += 1
            elif g < x:
                print("Your number is smaller!")
                tries += 1
            else:
                if tries == 1:
                    return f"Amazing! You guessed {x} first try!"
                else:
                    return f"Well done! The number was: {x}. You guessed the number in {tries} tries."

        except ValueError:
            print("Please enter a number (int) or type `exit`.\n")


def main():
    print(f"""\nYour goal is to guess the random number generated by the computer in the shortest guesses possible. Choose the level, how high the number that is generated can be, e.g: from 1 - 50. 
It will give you hints (higher or lower) if you guess incorrectly. Type `exit` at anytime to end the game.
""")

    while True:
        try:
            level = input("Choose a level (or 'exit'): ")
            if level.strip() == 'exit':
                return "You have exited the game."

            level = int(level)
            if level > 0:
                break
            else: 
                raise TypeError

        except TypeError:
            print("Please enter a valid number (int > 0) or type `exit`.\n") 
        except ValueError:
            print("Please enter a number (int) or type `exit`.\n") 

    x = random_num(level)   
    print(guessing(x))


if __name__ == "__main__":
    main()